//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 11:05:27 AM CET 
//


package itta;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the itta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LaClasseGenere_QNAME = new QName("", "laClasseGenere");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: itta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LaClasseGenere }
     * 
     */
    public LaClasseGenere createLaClasseGenere() {
        return new LaClasseGenere();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LaClasseGenere }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "laClasseGenere")
    public JAXBElement<LaClasseGenere> createLaClasseGenere(LaClasseGenere value) {
        return new JAXBElement<LaClasseGenere>(_LaClasseGenere_QNAME, LaClasseGenere.class, null, value);
    }

}
